---
sudo: required
dist: trusty
services:
  - docker
language: python
python:
  - "2.7"
env:
  global:
    - ANSIBLE_ROLES_PATH: ~/roles
  matrix:
    - distro: debian8
      init: /lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distro: ubuntu1604
      init: /lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distro: centos7
      init: /usr/lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
install:
  - pip install ansible==2.4.3.0
  - pip install ansible-lint==3.4.16
  - mkdir "${ANSIBLE_ROLES_PATH}"
  - printf "[defaults]\ninventory=hosts\nansible_roles=${ANSIBLE_ROLES_PATH}" > ~/.ansible.cfg
script:
  - ./build
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
