---
sudo: required
services:
  - docker
env:
  global:
    - ANSIBLE_ROLES_PATH: ~/roles
  matrix:
    - distro: ubuntu1604
      init: /lib/systemd/systemd
      run_opts: ""
    - distro: ubuntu1704
      init: /lib/systemd/systemd
      run_opts: ""
install:
  - sudo apt-get upgrade python -y
  - pip install ansible==2.3.0
  - pip install ansible-lint==3.4.10
  - mkdir "${ANSIBLE_ROLES_PATH}"
  - printf "[defaults]\nhostfile=hosts\nansible_roles=${ANSIBLE_ROLES_PATH}" > ~/.ansible.cfg
script:
  - ./build
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
