FROM debian:jessie

ENV TERM=xterm

# Install dependencies.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        sudo python \
    && rm -rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean
